/**
 * Per-page Markdown mirrors and the long-form llms-full.txt dump.
 *
 * These helpers are pure: each takes a normalized data object and
 * returns a Markdown string. No I/O. They power the Astro template's
 * `.md` mirror endpoints (one per item / category / tag / collection /
 * comparison / static page) and the concatenated `/llms-full.txt`
 * resource that ChatGPT, Claude, Perplexity, and other AI agents can
 * consume in a single fetch.
 *
 * Why expose Markdown twins?
 *
 * - HTML is laden with chrome (nav, footers, scripts, ads) that wastes
 *   an agent's context budget and confuses extraction.
 * - The `.md` mirror gives agents the page's substantive content with
 *   zero noise, taken straight from the YAML/Markdown source files.
 * - The HTML page advertises its mirror via
 *   `<link rel="alternate" type="text/markdown" href="/items/foo.md" />`.
 *
 * @see https://llmstxt.org/
 */

// Note: types are duplicated here as structural shapes rather than imported
// from `@ever-works/core` so this module stays a leaf dependency of plugin-seo.
// The shapes match `ItemData`, `Category`, `Tag`, `CollectionData`, and
// `ComparisonData` exactly.

/** Minimal item shape consumed by {@link renderItemMarkdown}. */
export interface MirrorItem {
    name: string;
    slug: string;
    description?: string;
    source_url?: string;
    category?: string | string[];
    tags?: string[];
    featured?: boolean;
    icon_url?: string;
    publisher?: string;
    updated_at?: string;
    markdown?: string;
}

/** Minimal category shape consumed by {@link renderCategoryMarkdown}. */
export interface MirrorCategory {
    id: string;
    name: string;
    description?: string;
}

/** Minimal tag shape consumed by {@link renderTagMarkdown}. */
export interface MirrorTag {
    id: string;
    name: string;
}

/** Minimal collection shape consumed by {@link renderCollectionMarkdown}. */
export interface MirrorCollection {
    id: string;
    slug: string;
    name: string;
    description?: string;
    icon_url?: string;
    items?: string[];
}

/** Minimal comparison shape consumed by {@link renderComparisonMarkdown}. */
export interface MirrorComparison {
    slug: string;
    title: string;
    summary?: string;
    item_a_name: string;
    item_b_name: string;
    item_a_slug: string;
    item_b_slug: string;
    dimensions?: ReadonlyArray<{ name?: string; title?: string }>;
    generated_at?: string;
}

/** Options shared by every renderer. */
export interface MarkdownMirrorOptions {
    /** Absolute base URL of the site (e.g. `'https://example.com'`). */
    baseUrl: string;
}

/** Strip a trailing slash from the base URL so we can `${base}/path`. */
function trimBase(base: string): string {
    return base.replace(/\/+$/, '');
}

function categoryLabel(cat: MirrorItem['category']): string {
    if (!cat) return '';
    return Array.isArray(cat) ? cat.filter(Boolean).join(', ') : cat;
}

/** Render a single directory item to Markdown. */
export function renderItemMarkdown(item: MirrorItem, options: MarkdownMirrorOptions): string {
    const base = trimBase(options.baseUrl);
    const canonicalUrl = `${base}/item/${item.slug}`;

    const lines: string[] = [];
    lines.push(`# ${item.name}`);
    lines.push('');
    if (item.description) {
        lines.push(`> ${item.description.replace(/\n+/g, ' ')}`);
        lines.push('');
    }

    const facts: string[] = [];
    if (item.source_url) facts.push(`- **URL:** ${item.source_url}`);
    const cat = categoryLabel(item.category);
    if (cat) facts.push(`- **Category:** ${cat}`);
    if (item.tags && item.tags.length > 0) facts.push(`- **Tags:** ${item.tags.join(', ')}`);
    if (item.featured) facts.push(`- **Featured:** yes`);
    if (item.publisher) facts.push(`- **Publisher:** ${item.publisher}`);
    if (item.updated_at) facts.push(`- **Updated:** ${item.updated_at}`);
    facts.push(`- **Canonical page:** ${canonicalUrl}`);
    lines.push(...facts);
    lines.push('');

    const body = (item.markdown ?? '').trim();
    if (body) {
        lines.push('## Details');
        lines.push('');
        lines.push(body);
        lines.push('');
    }

    lines.push('---');
    lines.push('');
    lines.push(`_This Markdown mirror is generated by Ever Works for AI agents. The canonical HTML page is at ${canonicalUrl}._`);
    lines.push('');

    return lines.join('\n');
}

/** Render a category page (items in the category) to Markdown. */
export function renderCategoryMarkdown(
    category: MirrorCategory | undefined,
    items: MirrorItem[],
    options: MarkdownMirrorOptions & { categoryRef: string }
): string {
    const base = trimBase(options.baseUrl);
    const canonicalUrl = `${base}/category/${options.categoryRef}`;
    const name = category?.name ?? options.categoryRef;

    const lines: string[] = [];
    lines.push(`# ${name}`);
    lines.push('');
    lines.push(`> Browse ${items.length} ${items.length === 1 ? 'item' : 'items'} in ${name}.`);
    lines.push('');
    if (category?.description) {
        lines.push(category.description);
        lines.push('');
    }

    if (items.length > 0) {
        lines.push('## Items');
        lines.push('');
        for (const item of items) {
            const url = `${base}/item/${item.slug}`;
            const desc = (item.description ?? '').replace(/\n+/g, ' ');
            lines.push(`- [${item.name}](${url})${desc ? ` — ${desc}` : ''}`);
        }
        lines.push('');
    }

    lines.push('---');
    lines.push('');
    lines.push(`_Canonical page: ${canonicalUrl}_`);
    lines.push('');
    return lines.join('\n');
}

/** Render a tag page (items with the tag) to Markdown. */
export function renderTagMarkdown(
    tag: MirrorTag | undefined,
    items: MirrorItem[],
    options: MarkdownMirrorOptions & { tagRef: string }
): string {
    const base = trimBase(options.baseUrl);
    const canonicalUrl = `${base}/tag/${options.tagRef}`;
    const name = tag?.name ?? options.tagRef;

    const lines: string[] = [];
    lines.push(`# ${name}`);
    lines.push('');
    lines.push(`> Browse ${items.length} ${items.length === 1 ? 'item' : 'items'} tagged with ${name}.`);
    lines.push('');

    if (items.length > 0) {
        lines.push('## Items');
        lines.push('');
        for (const item of items) {
            const url = `${base}/item/${item.slug}`;
            const desc = (item.description ?? '').replace(/\n+/g, ' ');
            lines.push(`- [${item.name}](${url})${desc ? ` — ${desc}` : ''}`);
        }
        lines.push('');
    }

    lines.push('---');
    lines.push('');
    lines.push(`_Canonical page: ${canonicalUrl}_`);
    lines.push('');
    return lines.join('\n');
}

/** Render a curated collection page to Markdown. */
export function renderCollectionMarkdown(
    collection: MirrorCollection,
    items: MirrorItem[],
    options: MarkdownMirrorOptions
): string {
    const base = trimBase(options.baseUrl);
    const slug = collection.slug || collection.id;
    const canonicalUrl = `${base}/collection/${slug}`;

    const lines: string[] = [];
    lines.push(`# ${collection.name}`);
    lines.push('');
    if (collection.description) {
        lines.push(`> ${collection.description.replace(/\n+/g, ' ')}`);
        lines.push('');
    }

    if (items.length > 0) {
        lines.push('## Items');
        lines.push('');
        for (const item of items) {
            const url = `${base}/item/${item.slug}`;
            const desc = (item.description ?? '').replace(/\n+/g, ' ');
            lines.push(`- [${item.name}](${url})${desc ? ` — ${desc}` : ''}`);
        }
        lines.push('');
    }

    lines.push('---');
    lines.push('');
    lines.push(`_Canonical page: ${canonicalUrl}_`);
    lines.push('');
    return lines.join('\n');
}

/** Render a comparison page (two items side-by-side) to Markdown. */
export function renderComparisonMarkdown(
    comparison: MirrorComparison,
    options: MarkdownMirrorOptions
): string {
    const base = trimBase(options.baseUrl);
    const canonicalUrl = `${base}/comparison/${comparison.slug}`;

    const lines: string[] = [];
    lines.push(`# ${comparison.title}`);
    lines.push('');
    if (comparison.summary) {
        lines.push(`> ${comparison.summary.replace(/\n+/g, ' ')}`);
        lines.push('');
    }

    lines.push('## Compared');
    lines.push('');
    lines.push(`- **${comparison.item_a_name}** — ${base}/item/${comparison.item_a_slug}`);
    lines.push(`- **${comparison.item_b_name}** — ${base}/item/${comparison.item_b_slug}`);
    lines.push('');

    if (comparison.dimensions && comparison.dimensions.length > 0) {
        lines.push('## Dimensions');
        lines.push('');
        for (const dim of comparison.dimensions) {
            const name = dim.name ?? dim.title ?? '';
            if (name) lines.push(`- ${name}`);
        }
        lines.push('');
    }

    lines.push('---');
    lines.push('');
    lines.push(`_Canonical page: ${canonicalUrl}_`);
    lines.push('');
    return lines.join('\n');
}

/**
 * Render a static page (about/help/etc.) to Markdown from raw frontmatter
 * metadata + body content, falling back to a default body when no
 * page exists in the data repo.
 */
export function renderStaticPageMarkdown(
    pageData: { metadata?: Record<string, unknown>; content?: string } | null,
    options: MarkdownMirrorOptions & { title: string; path: string; defaultContent?: string }
): string {
    const base = trimBase(options.baseUrl);
    const canonicalUrl = `${base}${options.path}`;

    const title = (pageData?.metadata?.title as string) || options.title;
    const description = (pageData?.metadata?.description as string) || '';
    const lastUpdated = (pageData?.metadata?.lastUpdated as string) || '';

    const body = (pageData?.content ?? options.defaultContent ?? '').trim();

    const lines: string[] = [];
    lines.push(`# ${title}`);
    lines.push('');
    if (description) {
        lines.push(`> ${description.replace(/\n+/g, ' ')}`);
        lines.push('');
    }
    if (lastUpdated) {
        lines.push(`_Last updated: ${lastUpdated}_`);
        lines.push('');
    }
    if (body) {
        lines.push(body);
        lines.push('');
    }
    lines.push('---');
    lines.push('');
    lines.push(`_Canonical page: ${canonicalUrl}_`);
    lines.push('');

    return lines.join('\n');
}

// ---------------------------------------------------------------------------
// llms-full.txt
// ---------------------------------------------------------------------------

/** Input shape for {@link generateLlmsFullTxt}. */
export interface LlmsFullTxtInput {
    /** Site name (rendered as the H1). */
    siteName: string;
    /** Absolute base URL of the site. */
    siteUrl: string;
    /** Optional one-line description rendered as a blockquote under the H1. */
    description?: string;
    /** All categories (rendered as a bulleted list under "## Categories"). */
    categories?: ReadonlyArray<{ id?: string; name?: string; count?: number }>;
    /** All tags (rendered as a bulleted list under "## Tags"). */
    tags?: ReadonlyArray<{ id?: string; name?: string; count?: number }>;
    /** All items (rendered with their full body content under "## Items"). */
    items?: ReadonlyArray<MirrorItem>;
    /** All comparisons (rendered under "## Comparisons"). */
    comparisons?: ReadonlyArray<MirrorComparison>;
    /**
     * Cap on the number of items rendered with full bodies. Defaults
     * to 500. Sites with thousands of items can exceed reasonable
     * response sizes; agents that need every item should fall back to
     * /items.json or per-page .md mirrors.
     */
    maxItemsWithBody?: number;
}

/**
 * Render the entire directory as a single Markdown document suitable
 * for serving at `/llms-full.txt`.
 *
 * Format mirrors the llmstxt.org convention:
 *
 *   # Site
 *   > Description
 *   ## Categories
 *   ## Tags
 *   ## Items
 *   ### Item 1
 *   ### Item 2
 *   ## Comparisons
 */
export function generateLlmsFullTxt(input: LlmsFullTxtInput): string {
    const cap = input.maxItemsWithBody ?? 500;
    const baseUrl = trimBase(input.siteUrl);

    const lines: string[] = [];
    lines.push(`# ${input.siteName}`);
    lines.push('');
    if (input.description) {
        lines.push(`> ${input.description}`);
        lines.push('');
    }
    lines.push(`Generated: ${new Date().toISOString()}`);
    lines.push(`Items: ${input.items?.length ?? 0}`);
    if (baseUrl) lines.push(`Canonical site: ${baseUrl}`);
    lines.push('');

    if (input.categories && input.categories.length > 0) {
        lines.push('## Categories');
        lines.push('');
        for (const c of input.categories) {
            const name = c.name ?? c.id ?? '';
            if (!name) continue;
            lines.push(`- ${name}${c.count ? ` — ${c.count} items` : ''}`);
        }
        lines.push('');
    }

    if (input.tags && input.tags.length > 0) {
        lines.push('## Tags');
        lines.push('');
        const top = input.tags.slice(0, 100);
        for (const t of top) {
            const name = t.name ?? t.id ?? '';
            if (!name) continue;
            lines.push(`- ${name}${t.count ? ` — ${t.count} items` : ''}`);
        }
        if (input.tags.length > top.length) {
            lines.push('');
            lines.push(`_…and ${input.tags.length - top.length} more (see ${baseUrl}/tags)._`);
        }
        lines.push('');
    }

    if (input.items && input.items.length > 0) {
        lines.push('## Items');
        lines.push('');
        const cappedItems = input.items.slice(0, cap);
        for (const item of cappedItems) {
            const md = renderItemMarkdown(item, { baseUrl });
            lines.push(demoteAndStrip(md));
            lines.push('');
            lines.push('---');
            lines.push('');
        }

        if (input.items.length > cappedItems.length) {
            lines.push(
                `_${input.items.length - cappedItems.length} additional items omitted to keep this file usable. See ${baseUrl}/items.json or per-item .md mirrors at ${baseUrl}/item/<slug>.md._`
            );
            lines.push('');
        }
    }

    if (input.comparisons && input.comparisons.length > 0) {
        lines.push('## Comparisons');
        lines.push('');
        for (const cmp of input.comparisons) {
            const md = renderComparisonMarkdown(cmp, { baseUrl });
            lines.push(demoteAndStrip(md));
            lines.push('');
            lines.push('---');
            lines.push('');
        }
    }

    return lines.join('\n');
}

/**
 * Demote heading levels by one and strip the trailing
 * "_This Markdown mirror is generated by…_" / "_Canonical page:_" footer
 * from a per-page mirror so it composes cleanly inside llms-full.txt.
 */
function demoteAndStrip(md: string): string {
    return md
        .split('\n')
        .filter(
            (line) =>
                !/^_This Markdown mirror is generated by Ever Works/.test(line) &&
                !/^_Canonical page:/.test(line)
        )
        .join('\n')
        .replace(/^(#{1,5}) /gm, '$1# ')
        .replace(/\n{3,}/g, '\n\n')
        .trim();
}
