/**
 * Category data types.
 * Parsed from `.content/categories.yml` or `.content/categories/categories.yml`.
 */

/** A category definition */
export interface CategoryData {
    /** Unique identifier (lowercase, kebab-case) */
    id: string;

    /** Human-readable display name */
    name: string;

    /** Optional description */
    description?: string;

    /** Optional URL to category icon */
    icon_url?: string;

    /** Optional inline SVG icon generated by the platform */
    icon_svg?: string;

    /** Lower numbers appear first in platform-managed taxonomies */
    priority?: number;

    /** Optional URL to category image (used in some themes for card backgrounds) */
    image_url?: string;
}

/** Category with computed item count */
export interface CategoryWithCount extends CategoryData {
    /** Number of approved items in this category */
    count: number;
}
