/**
 * Collection data type.
 * Parsed from `.content/collections.yml`.
 */

/** A curated collection of items */
export interface CollectionData {
    /** Unique identifier */
    id: string;

    /** URL-safe slug */
    slug: string;

    /** Human-readable display name */
    name: string;

    /** Description of what this collection contains */
    description: string;

    /** Optional URL to collection icon */
    icon_url?: string;

    /** Optional inline SVG icon generated by the platform */
    icon_svg?: string;

    /** Lower numbers appear first in platform-managed taxonomies */
    priority?: number;

    /** Item slugs that belong to this collection */
    items?: string[];

    /** Number of items in this collection (from YAML or computed) */
    item_count?: number;

    /** Whether this collection is active and visible */
    isActive?: boolean;

    /** Creation timestamp */
    created_at?: string;

    /** Last update timestamp */
    updated_at?: string;
}
