import { describe, expect, it } from 'vitest';
import {
    generateLlmsFullTxt,
    renderCategoryMarkdown,
    renderCollectionMarkdown,
    renderComparisonMarkdown,
    renderItemMarkdown,
    renderStaticPageMarkdown,
    renderTagMarkdown,
} from '../markdown-mirror.js';

describe('renderItemMarkdown', () => {
    it('emits H1, blockquote description, fact list, and footer', () => {
        const md = renderItemMarkdown(
            {
                name: 'Cursor',
                slug: 'cursor',
                description: 'AI-first code editor.',
                source_url: 'https://cursor.sh',
                category: 'AI',
                tags: ['ai', 'editor'],
                featured: true,
                publisher: 'Cursor Inc.',
                updated_at: '2026-05-01 12:00',
                markdown: '## Why use it?\n\nIt is great.',
            },
            { baseUrl: 'https://example.com/' }
        );

        expect(md).toMatch(/^# Cursor/);
        expect(md).toContain('> AI-first code editor.');
        expect(md).toContain('- **URL:** https://cursor.sh');
        expect(md).toContain('- **Category:** AI');
        expect(md).toContain('- **Tags:** ai, editor');
        expect(md).toContain('- **Featured:** yes');
        expect(md).toContain('- **Publisher:** Cursor Inc.');
        expect(md).toContain('- **Updated:** 2026-05-01 12:00');
        expect(md).toContain('- **Canonical page:** https://example.com/item/cursor');
        expect(md).toContain('## Details');
        expect(md).toContain('## Why use it?');
        expect(md).toMatch(/_This Markdown mirror is generated by Ever Works/);
    });

    it('handles arrays of categories', () => {
        const md = renderItemMarkdown(
            { name: 'X', slug: 'x', category: ['ai', 'ml'] },
            { baseUrl: 'https://example.com' }
        );
        expect(md).toContain('- **Category:** ai, ml');
    });

    it('omits sections with no data', () => {
        const md = renderItemMarkdown({ name: 'Bare', slug: 'bare' }, { baseUrl: 'https://example.com' });
        expect(md).toMatch(/^# Bare/);
        expect(md).not.toContain('## Details');
        expect(md).not.toContain('**URL:**');
    });

    it('strips trailing slash from baseUrl when building canonical URL', () => {
        const md = renderItemMarkdown({ name: 'X', slug: 'x' }, { baseUrl: 'https://example.com////' });
        expect(md).toContain('https://example.com/item/x');
        expect(md).not.toContain('com//item');
    });
});

describe('renderCategoryMarkdown', () => {
    it('lists items as Markdown links under "## Items"', () => {
        const md = renderCategoryMarkdown(
            { id: 'ai', name: 'AI Tools' },
            [
                { name: 'Cursor', slug: 'cursor', description: 'AI editor.' },
                { name: 'Claude', slug: 'claude' },
            ],
            { baseUrl: 'https://example.com', categoryRef: 'ai' }
        );

        expect(md).toMatch(/^# AI Tools/);
        expect(md).toContain('> Browse 2 items in AI Tools.');
        expect(md).toContain('- [Cursor](https://example.com/item/cursor) — AI editor.');
        expect(md).toContain('- [Claude](https://example.com/item/claude)');
        expect(md).toContain('_Canonical page: https://example.com/category/ai_');
    });

    it('renders 0-item categories without an Items section', () => {
        const md = renderCategoryMarkdown({ id: 'empty', name: 'Empty' }, [], {
            baseUrl: 'https://example.com',
            categoryRef: 'empty',
        });
        expect(md).toContain('> Browse 0 items in Empty.');
        expect(md).not.toContain('## Items');
    });

    it('falls back to categoryRef when no category metadata is provided', () => {
        const md = renderCategoryMarkdown(undefined, [], {
            baseUrl: 'https://example.com',
            categoryRef: 'mystery',
        });
        expect(md).toMatch(/^# mystery/);
    });
});

describe('renderTagMarkdown', () => {
    it('lists tagged items', () => {
        const md = renderTagMarkdown(
            { id: 'ai', name: 'ai' },
            [{ name: 'Cursor', slug: 'cursor', description: 'Editor.' }],
            { baseUrl: 'https://example.com', tagRef: 'ai' }
        );
        expect(md).toContain('> Browse 1 item tagged with ai.');
        expect(md).toContain('- [Cursor](https://example.com/item/cursor) — Editor.');
    });
});

describe('renderCollectionMarkdown', () => {
    it('renders the collection name, description, and items', () => {
        const md = renderCollectionMarkdown(
            { id: 'best-ai', slug: 'best-ai', name: 'Best AI Tools', description: 'Hand-picked.' },
            [{ name: 'Cursor', slug: 'cursor', description: 'AI editor.' }],
            { baseUrl: 'https://example.com' }
        );
        expect(md).toContain('# Best AI Tools');
        expect(md).toContain('> Hand-picked.');
        expect(md).toContain('- [Cursor](https://example.com/item/cursor) — AI editor.');
        expect(md).toContain('_Canonical page: https://example.com/collection/best-ai_');
    });
});

describe('renderComparisonMarkdown', () => {
    it('renders both contestants and the listed dimensions', () => {
        const md = renderComparisonMarkdown(
            {
                slug: 'cursor-vs-windsurf',
                title: 'Cursor vs Windsurf',
                summary: 'Two AI editors compared.',
                item_a_name: 'Cursor',
                item_b_name: 'Windsurf',
                item_a_slug: 'cursor',
                item_b_slug: 'windsurf',
                dimensions: [{ name: 'Performance' }, { name: 'Pricing' }],
            },
            { baseUrl: 'https://example.com' }
        );

        expect(md).toContain('# Cursor vs Windsurf');
        expect(md).toContain('> Two AI editors compared.');
        expect(md).toContain('- **Cursor** — https://example.com/item/cursor');
        expect(md).toContain('- **Windsurf** — https://example.com/item/windsurf');
        expect(md).toContain('## Dimensions');
        expect(md).toContain('- Performance');
        expect(md).toContain('- Pricing');
    });
});

describe('renderStaticPageMarkdown', () => {
    it('uses the page metadata title/description and falls back to the supplied default body', () => {
        const md = renderStaticPageMarkdown(
            // No `content` field, so the renderer should fall back to options.defaultContent.
            { metadata: { title: 'About Us', description: 'Who we are.' } },
            {
                title: 'About',
                path: '/about',
                baseUrl: 'https://example.com',
                defaultContent: 'No content yet.',
            }
        );
        expect(md).toContain('# About Us');
        expect(md).toContain('> Who we are.');
        expect(md).toContain('No content yet.');
        expect(md).toContain('_Canonical page: https://example.com/about_');
    });

    it('handles a null pageData with the default content fallback', () => {
        const md = renderStaticPageMarkdown(null, {
            title: 'Cookies',
            path: '/cookies',
            baseUrl: 'https://example.com',
            defaultContent: 'Fallback body.',
        });
        expect(md).toContain('# Cookies');
        expect(md).toContain('Fallback body.');
    });
});

describe('generateLlmsFullTxt', () => {
    it('emits site preamble + sections in order', () => {
        const md = generateLlmsFullTxt({
            siteName: 'Demo',
            siteUrl: 'https://example.com',
            description: 'A demo directory.',
            categories: [{ id: 'ai', name: 'AI', count: 5 }],
            tags: [{ id: 'ml', name: 'ml', count: 3 }],
            items: [
                {
                    name: 'Cursor',
                    slug: 'cursor',
                    description: 'AI editor.',
                    source_url: 'https://cursor.sh',
                    markdown: '## Body\n\nOK.',
                },
            ],
            comparisons: [
                {
                    slug: 'a-vs-b',
                    title: 'A vs B',
                    item_a_name: 'A',
                    item_b_name: 'B',
                    item_a_slug: 'a',
                    item_b_slug: 'b',
                },
            ],
        });

        // Site preamble.
        expect(md).toMatch(/^# Demo/);
        expect(md).toContain('> A demo directory.');
        expect(md).toContain('Items: 1');
        expect(md).toContain('Canonical site: https://example.com');

        // Section headings.
        expect(md).toContain('## Categories');
        expect(md).toContain('- AI — 5 items');
        expect(md).toContain('## Tags');
        expect(md).toContain('- ml — 3 items');
        expect(md).toContain('## Items');
        // Per-item content was demoted from H1 to H2.
        expect(md).toContain('## Cursor');
        // The per-item footer line was stripped (no "Markdown mirror is generated" inside the dump).
        expect(md).not.toContain('This Markdown mirror is generated by Ever Works');
        expect(md).toContain('## Comparisons');
    });

    it('caps the items section to maxItemsWithBody and notes the omission', () => {
        const items = Array.from({ length: 750 }, (_, i) => ({
            name: `Item ${i}`,
            slug: `item-${i}`,
        }));
        const md = generateLlmsFullTxt({
            siteName: 'Big',
            siteUrl: 'https://example.com',
            items,
            maxItemsWithBody: 3,
        });
        expect(md).toContain('## Item 0');
        expect(md).toContain('## Item 2');
        expect(md).not.toContain('## Item 3');
        expect(md).toContain('747 additional items omitted');
    });

    it('emits the "…and N more" footer for the tags section when over 100', () => {
        const tags = Array.from({ length: 150 }, (_, i) => ({ id: `t${i}`, name: `tag-${i}` }));
        const md = generateLlmsFullTxt({
            siteName: 'Big',
            siteUrl: 'https://example.com',
            tags,
            items: [],
        });
        expect(md).toContain('- tag-0');
        expect(md).toContain('- tag-99');
        expect(md).not.toContain('- tag-100');
        expect(md).toContain('…and 50 more');
    });
});
