/**
 * Public llms.txt endpoint per the public llms.txt convention
 * (https://llmstxt.org). Provides downstream LLM agents with a
 * machine-readable manifest of the directory and pointers to the canonical
 * data dump at /items.json.
 *
 * Pairs with the Ever Works zero-friction onboarding feature so that any
 * directory built by an agent through `POST /api/register-work` is
 * immediately discoverable by other agents.
 */

import type { APIRoute } from 'astro';
import { getContent } from '../lib/content';

export const GET: APIRoute = async () => {
    const { items, config } = await getContent();

    const siteUrl = (config.app_url ?? '').replace(/\/$/, '');
    const name = config.company_name ?? 'Ever Works Directory';
    const description =
        (config as { description?: string; tagline?: string }).description ??
        (config as { tagline?: string }).tagline ??
        `A curated directory of ${items.length} ${items.length === 1 ? 'item' : 'items'}.`;

    const lines: string[] = [
        `# ${name}`,
        '',
        description,
        '',
        '## Canonical data',
        '',
        `- [Full items index](${siteUrl}/items.json) — JSON dump of every item with its category, tags, and link.`,
        `- [Sitemap](${siteUrl}/sitemap-index.xml)`,
        `- [Atom feed](${siteUrl}/atom.xml)`,
        '',
        '## About',
        '',
        'This site was generated by the [Ever Works](https://ever.works) platform. Agents that want to build their own directory can use the zero-friction onboarding endpoint at `https://api.ever.works/api/register-work` — see https://docs.ever.works/agent-services/zero-friction-onboarding for details.',
        ''
    ];

    return new Response(lines.join('\n'), {
        status: 200,
        headers: {
            'Content-Type': 'text/plain; charset=utf-8',
            'Cache-Control': 'public, max-age=300, s-maxage=900'
        }
    });
};
